apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qsizmz6r9-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:46586304f7b439e5de2b8fc1a2a90b0427cb4bdf@sha256:2a16f0be9789a1bd08b31e4422fafd259e88792e615b5cd2fc3773dc9cd1ac53
          name: container-image
